---
version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/appdata/grafana/data:/var/lib/grafana
    restart: unless-stopped
    
volumes:
  grafana-data:
    driver: local
