---
version: "3"
services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  yacht:
