# https://docs.n8n.io/
---
version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
    volumes:
      - n8n_storage:/home/node/.n8n
#      - ./data/files:/files

volumes:
  n8n_storage:
    driver: local
