--- # https://docs.n8n.io/
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - TZ="America/Sao_Paulo"
    volumes:
      - ./n8n_data:/home/node/.n8n

# volumes:
#   n8n_storage:
#     driver: local
