---
version: "3"
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
