---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=[KEY]
      - WIREGUARD_PRESHARED_KEY=[KEY]
      - WIREGUARD_ADDRESSES=10.99.99.99/32,ff:ff:ff...:ff/128 #WIREGUARD_ADDRESSES may only contain an IPv6 address (such as ff:ff.../128) if your container setup supports IPv6. To do so, see the IPv6 document. Otherwise, remove the IPv6 address from WIREGUARD_ADDRESSES
      - SERVER_COUNTRIES=Netherlands
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./gluetun:/gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
    volumes:
      - ./qbit/config:/config
      - ./qbit/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    network_mode: "service:gluetun"
    container_name: jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /jackett/config:/config
      - /jackett/blackhole:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
