---
version: "3.5"
services:
  wikijs:
    container_name: wikijs
    image: lscr.io/linuxserver/wikijs:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_TYPE=sqlite #optional mysql, postgres, mariadb, mssql or sqlite
    volumes:
      - ./wikijs/config:/config
      - ./wikijs/data:/data
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '0.8GB'


#--- Alternative with POSTGRES
#version: "3"
#services:
#
#  db:
#    image: postgres:15-alpine
#    environment:
#      POSTGRES_DB: wiki
#      POSTGRES_PASSWORD: wikijsrocks
#      POSTGRES_USER: wikijs
#    logging:
#      driver: "none"
#    restart: unless-stopped
#    volumes:
#      - db-data:/var/lib/postgresql/data
#
#  wiki:
#    image: ghcr.io/requarks/wiki:2
#    depends_on:
#      - db
#    environment:
#      DB_TYPE: postgres
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_USER: wikijs
#      DB_PASS: wikijsrocks
#      DB_NAME: wiki
#    restart: unless-stopped
#    ports:
#      - "80:3000"
#
#volumes:
#  db-data: