---
services:
  mariadb: #https://hub.docker.com/_/mariadb
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root #user: root, password: root
      - MARIADB_DATABASE=default #default database
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: --innodb_buffer_pool_instances=4 --innodb-buffer-pool-size=2G --innodb_log_file_size=1G --key_buffer_size=256M --query_cache_size=64M

  phpmyadmin: #https://hub.docker.com/_/phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
