---
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root #user: root, password: root
      - MARIADB_DATABASE=default
    volumes:
      - ./mariadb-data:/var/lib/mysql

  phpmyadmin: #host is: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
