---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - [IP_TAILSCALE]:2222:2222  # magnetico
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn #or other
      - SERVER_COUNTRIES=Netherlands
      - VPN_TYPE=openvpn #or wireguard
      - OPENVPN_USER=[USER]
      - OPENVPN_PASSWORD=[PASSWORD]
      - TZ=UTC
  magnetico:
    image: ghcr.io/fabricio20/magnetico/magneticod:latest
    network_mode: service:gluetun
    restart: always