---
version: "3"
services:
  qbit:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    restart: unless-stopped
    privileged: true
    environment:
      - VPN_USERNAME= #CHANGEME ###
      - VPN_PASSWORD= #CHANGEME ###
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - PUID=1000 #optional
      - PGID=100 #optional
      - WEBUI_PORT_ENV=8080 #optional
      - INCOMING_PORT_ENV=8999 #optional
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - ./config:/config
      - ./blackhole:/blackhole
      - /mnt/user/Downloads/:/downloads

  # App: https://github.com/Jackett/Jackett
  # Image: https://github.com/DyonR/docker-Jackettvpn
  jackett:
    image: dyonr/jackettvpn
    container_name: jackettvpn
    restart: unless-stopped
    privileged: true
    environment:
      - VPN_USERNAME= #CHANGEME ###
      - VPN_PASSWORD= #CHANGEME ###
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - PUID=99 #optional
      - PGID=100 #optional
      #- WEBUI_PASSWORD= #PASS_HERE #optional
    ports:
      - 9117:9117
    volumes:
      - ./config:/config
      - ./blackhole:/blackhole


#After Start qBit: Tools > Options
#                    - Automatically add torrents from:
#                    - /blackhole : Monitored Folder
#
#After Start Jackett: http://192.168.1.23:9117/UI/Dashboard
#                       - Jackett Configuration
#                       - Blackhole directory: /blackhole