---
version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=UTC
    volumes:
      - ./sonarr:/config
      - /mnt/storage/series:/series:rshared
      - ./downloads:/downloads
    ports:
      - 127.0.0.1:2703:8989
  radarr:
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=UTC
    volumes:
      - ./radarr:/config
      - /mnt/storage/movies:/movies:rshared
      - ./downloads:/downloads
    ports:
      - 127.0.0.1:2704:7878