---
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root #user: root, password: root
      - MARIADB_DATABASE=default
    volumes:
      - ./mariadb-data:/var/lib/mysql

#    environment:
#      (Optional) remove this section, when using random, or empty root password
#      (Optional) when using random, or empty root password
#      - MARIADB_RANDOM_ROOT_PASSWORD=true
#      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
#      - MARIADB_DATABASE=your-database
#      - MARIADB_USER=your-user
#      - MARIADB_PASSWORD=your-password
# (Optional) when using custom volume
#volumes:
#  mariadb-data:
# (Optional) when using custom network
# networks:
#   yournetwork:
#     external: true