---
version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      - TZ='America/Sao_Paulo'
      - WEBPASSWORD='your-secret-password' #WEBPASSWORD: 'set a secure password here or it will be random'
      - WEB_PORT: '82' # Change port 80 (default) to 82 portal admin
    volumes: 
      - './etc-pihole:/etc/pihole' # Volumes store your data between container upgrades
      - './etc-dnsmasq.d:/etc/dnsmasq.d' # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always
