mqtt:
  enabled: false
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://IP_CAMERA_HERE:554/h264Preview_01_main
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
    record:
      enabled: True
      retain:
        days: 7
        mode: all
detectors:
  cpu1:
    type: cpu
    num_threads: 3