mqtt:
  enabled: false
cameras:
  FrontCam:
    ffmpeg:
      inputs:
        - path: rtsp://IP_HERE:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
detectors:
  cpu1:
    type: cpu
    num_threads: 3
#Global Object Settings
rtmp:
  enabled: false
birdseye:
  enabled: True
  mode: continuous
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.75
      min_area: 5000
      max_area: 100000
snapshots:
  enabled: True
  retain:
    default: 1
record:
  enabled: True
  expire_interval: 10
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 5
ffmpeg:
  hwaccel_args: preset-vaapi
